#!/usr/bin/env python

import sys
from pathlib import Path
from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader
from pyparam import params
from box import Box

spec = spec_from_loader("qsub", SourceFileLoader("qsub", str(Path(__file__).parent.resolve() / 'qsub')))
qsub = module_from_spec(spec)
spec.loader.exec_module(qsub)

params.force.desc = 'The job id'
params.force.type = str
opts = params._parse(dict_wrapper = Box)

sys.stderr.write('Killing %s ...' % opts.force)
qsub.SgeJob().kill(opts.force)
