#!/usr/bin/env python

import sys
from os import path

fakepid = sys.argv[1]
piddb = path.join(path.dirname(__file__), 'qsub.queue.txt')
if path.isfile(piddb):
	with open(piddb) as f:
		pids = [line.strip() for line in f]
	del pids[pids.index(fakepid)]
	
	with open(piddb, 'w') as f:
		f.write('\n'.join(pids))