#!/usr/bin/env python

import sys, hashlib
from os import path, system

cmd = sys.argv[1]
fakepid = str(int(hashlib.md5(cmd).hexdigest()[:8], 16))

piddb = path.join(path.dirname(__file__), 'qsub.queue.txt')
if not path.isfile(piddb):
	pids = []
else:
	with open(piddb) as f:
		pids = [line.strip() for line in f]

pids.append(fakepid)
with open(piddb, 'w') as f:
	f.write('\n'.join(pids))

outfile = path.join(path.dirname(cmd), 'job.stdout')
with open(outfile, 'w') as f:
	f.write('Your job %s ("job.name") has been submitted' % fakepid)
	
system ('bash ' + cmd + ' &')


