#!/usr/bin/env python

import sys
import cmdy
from pyppl.utils import killtree
from hashlib import md5
from pathlib import Path
from box import Box
from pyparam import params

DATABASE = Path(__file__).resolve().parent / 'sge.jobs.log'

class SgeJob:

	def __init__(self, script = ''):
		if not DATABASE.exists():
			DATABASE.write_text('')
		self.job        = SgeJob._jobNameFromSgeScript(script)
		self.shouldfail = SgeJob._shouldFail(script)
		md5job          = md5(self.job.encode()).hexdigest()
		self.jobid      = str(int(md5job, 16))
		self.script     = script

	@property
	def jobs(self):
		return [tuple(line.split(',')) for line in DATABASE.read_text().splitlines()]

	@jobs.setter
	def jobs(self, jobids):
		DATABASE.write_text('\n'.join(','.join(jid) for jid in jobids))

	@staticmethod
	def _shouldFail(script):
		if not script:
			return False
		with open(script) as fscript:
			for line in fscript:
				if line.startswith('# ShouldFail'):
					return True
		return False

	@staticmethod
	def _jobNameFromSgeScript(script):
		if not script:
			return ''
		with open(script) as fscript:
			for line in fscript:
				if line.startswith('#$ -N'):
					return line[5:].strip()

	@staticmethod
	def _outerrFromSgeScript(script):
		if not script:
			return (None, None)
		outfile = None
		errfile = None
		with open(script) as fscript:
			for line in fscript:
				if line.startswith('#$ -o'):
					outfile = line[5:].strip()
				elif line.startswith('#$ -e'):
					errfile = line[5:].strip()
		return outfile, errfile

	def submit(self):
		if self.shouldfail:
			return
		sys.stdout.write("Your job %s (%s) has been submitted" % (self.jobid, self.job))
		outfile, errfile = SgeJob._outerrFromSgeScript(self.script)
		c = cmdy.bash(c = 'bash ' + self.script + '; sleep 3; %s --force %s' %
			(Path(__file__).resolve().parent / 'qdel', self.jobid),
				_bg = True, _out = outfile, _err = errfile)
		if not self.isRunning():
			self.jobs = self.jobs + [(self.jobid, str(c.pid))]

	def isRunning(self, jobid = None):
		jobid = jobid or self.jobid
		return any(jobid == jid for jid, _ in self.jobs)

	def kill(self, jobid = None):
		jobid = jobid or self.jobid
		jobs = []
		for jid, pid in self.jobs:
			if jid == jobid:
				pid = int(pid)
				if pid > 0:
					sys.stdout.write('Job %s (%s) is killed.' % (jobid, pid))
					try:
						killtree(pid)
					except:
						pass
			else:
				jobs.append((jid, pid))
		self.jobs = jobs

if __name__ == "__main__":
	params._.desc = 'Job to submit'
	opts = params._parse(dict_wrapper=Box)
	SgeJob(opts._).submit()
