#!/usr/bin/env python

import sys, hashlib, subprocess
from os import path

cmd = sys.argv[1]
fakepid = str(int(hashlib.md5(cmd.encode()).hexdigest()[:8], 16))

piddb = path.join(path.dirname(__file__), 'sbatch.queue.txt')
if not path.isfile(piddb):
	pids = []
else:
	with open(piddb) as f:
		pids = [line.strip() for line in f]

pids.append(fakepid)
with open(piddb, 'w') as f:
	f.write('\n'.join(pids))

sys.stdout.write('Submitted batch job %s' % fakepid)
	
subprocess.Popen(['bash', cmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE)


