#!/usr/bin/env python

import sys
from pathlib import Path
from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader
from pyparam import params
from box import Box

spec = spec_from_loader("sbatch", SourceFileLoader("sbatch", str(Path(__file__).parent.resolve() / 'sbatch')))
sbatch = module_from_spec(spec)
spec.loader.exec_module(sbatch)

params._.desc = 'The job id'
params._.type = str
opts = params._parse(dict_wrapper = Box)

sbatch.SlurmJob().kill(opts._)
