#!/usr/bin/env python

import sys
from os import path

# scancel jobid
job = sys.argv[1]

piddb = path.join(path.dirname(__file__), 'sbatch.queue.txt')
if not path.isfile(piddb):
	pids = []
else:
	with open(piddb) as f:
		pids = [line.strip() for line in f]

if job in pids:
	del pids[pids.index(job)]

with open(piddb, 'w') as f:
	f.write('\n'.join(pids))

sys.stdout.write('Your job %s ("job.name") has been deleted' % job)