#!/usr/bin/env python

import sys
from pathlib import Path
from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader
from pyparam import params
from diot import Diot

spec = spec_from_loader("sbatch", SourceFileLoader("sbatch", str(Path(__file__).parent.resolve() / 'sbatch')))
sbatch = module_from_spec(spec)
spec.loader.exec_module(sbatch)

params.j.desc = 'The job id'
params.j.type = str
opts = params._parse(dict_wrapper = Diot)

if sbatch.SlurmJob().isRunning(opts.j):
	sys.stdout.write('Job %s is running.' % opts.j)
	sys.exit(0)
sys.stdout.write('Job %s is not running.' % opts.j)
sys.exit(1)
