#!/usr/bin/env python

import sys
from os import path

fakepid = sys.argv[2]

piddb = path.join(path.dirname(__file__), 'sbatch.queue.txt')
if not path.isfile(piddb):
	sys.exit(1)
else:
	with open(piddb) as f:
		pids = [line.strip() for line in f]
	running = fakepid in pids
	if running:
		print '# the head line'
		print fakepid, 'whatever'