# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='pipen',
    version='0.0.1',
    description='A pipeline framework for python',
    python_requires='==3.*,>=3.7.0',
    project_urls={
        "homepage": "https://github.com/pwwang/pipen",
        "repository": "https://github.com/pwwang/pipen"
    },
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={"console_scripts": ["pipen = pipen.cli:main"]},
    packages=['pipen', 'pipen.channel'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'cached-property==1.*', 'diot', 'enlighten==1.*', 'liquidpy',
        'more-itertools==8.*', 'pandas==1.*', 'pyparam', 'python-simpleconf',
        'python-slugify==4.*', 'rich==9.*', 'simplug', 'siuba==0.*',
        'toml==0.*,>=0.10.0', 'uvloop==0.*', 'varname', 'xqute'
    ],
    extras_require={"dev": ["jinja2==2.*,>=2.0.0", "pytest", "pytest-cov"]},
)
