import sys, unittest, os, glob
rootdir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, rootdir)
from pyppl.helpers import logger

class TestLogger (unittest.TestCase):
	
	def testGetColorFromTheme (self):
		theme = logger.themes['greenOnBlack']
		self.assertEqual (logger._getColorFromTheme('DONE', theme), tuple([logger.colors.bold + logger.colors.green]*2))
		self.assertEqual (logger._getColorFromTheme('DEBUG', theme), tuple([logger.colors.bold + logger.colors.black]*2))
		self.assertEqual (logger._getColorFromTheme('>>>>>>>', theme), tuple([logger.colors.bold + logger.colors.cyan, logger.colors.bold + logger.colors.underline + logger.colors.cyan]))
		self.assertEqual (logger._getColorFromTheme('INFO', theme), tuple([logger.colors.green]*2))
		self.assertEqual (logger._getColorFromTheme('DEPENDS', theme), tuple([logger.colors.green]*2))
		self.assertEqual (logger._getColorFromTheme('ERRRRR', theme), tuple([logger.colors.red]*2))
		self.assertEqual (logger._getColorFromTheme('WARNING', theme), tuple([logger.colors.bold + logger.colors.yellow]*2))
		self.assertEqual (logger._getColorFromTheme('CACHED', theme), tuple([logger.colors.yellow]*2))
		self.assertEqual (logger._getColorFromTheme('234', theme), tuple([logger.colors.white]*2))
	
	def testFilter(self):
		log = logger.getLogger(levels=None)
		log.info('You should not see this1')
		log.info('You should not see this2')
		
		logger.getLogger(levels="ONLY")
		log.info('[No]You cannot see this')
		log.info('[ONLY]You can see this')
		log.info('[   ONLY]You can see this, too')
		
		logger.getLogger(levels='all')
		log.debug('You see this, debug')
		log.warning('You see this, warning')
		log.error('You see this, error')
		log.info('You see this, info')
		
		logger.getLogger(levels='basic')
		log.info('[>>>>>>>]You see this')
		log.info('[NO]You don\'t see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You don\'t see this')
		log.info('[OUTPUT]You don\'t see this')
		log.info('[SUBMIT]You don\'t see this')
		log.info('[P.ARGS]You don\'t see this')
		log.info('[P.PROPS]You don\'t see this')
		log.info('[JOBDONE]You don\'t see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(levels = 'normal')
		log.info('[>>>>>>>]You see this')
		log.info('[NO]You don\'t see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You don\'t see this')
		log.info('[P.PROPS]You don\'t see this')
		log.info('[JOBDONE]You don\'t see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(levels = 'nodebug')
		log.info('[>>>>>>>]You see this')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
	def testFormatter(self):
		log = logger.getLogger(theme = False)
		log.info('[>>>>>>>]You see this')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = True)
		log.info('[>>>>>>>]greenOnBlack')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = 'blueOnBlack')
		log.info('[>>>>>>>]blueOnBlack')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = 'magentaOnBlack')
		log.info('[>>>>>>>]magentaOnBlack')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = 'greenOnWhite')
		log.info('[>>>>>>>]greenOnWhite')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = 'blueOnWhite')
		log.info('[>>>>>>>]blueOnWhite')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = 'magentaOnWhite')
		log.info('[>>>>>>>]magentaOnWhite')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
		logger.getLogger(theme = {
			'DEPENDS': logger.colors.yellow,
			'starts:STD': "colors.cyan + colors.underline"
		})
		log.info('[>>>>>>>]Customized')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You don\'t see this')
		
	def testLogfile (self):
		logger.getLogger(logfile = '/dev/null')
		logger.logger.info('[>>>>>>>]testLogfile')
		logger.logger.info('[NO]You don\'t see this')
		logger.logger.info('[_NO]But you see this')
		logger.logger.info('[DEPENDS]You see this')
		logger.logger.info('[STDOUT]You see this')
		logger.logger.info('[STDERR]You see this')
		logger.logger.info('[ERROR]You see this')
		logger.logger.info('[INFO]You see this')
		logger.logger.info('[DONE]You see this')
		logger.logger.info('[RUNNING]You see this')
		logger.logger.info('[CACHED]You see this')
		logger.logger.info('[EXPORT]You see this')
		logger.logger.info('[INPUT]You see this')
		logger.logger.info('[OUTPUT]You see this')
		logger.logger.info('[SUBMIT]You see this')
		logger.logger.info('[P.ARGS]You see this')
		logger.logger.info('[P.PROPS]You see this')
		logger.logger.info('[JOBDONE]You see this')
		logger.logger.info('[DEBUG]You don\'t see this')
	
	def testLvlDiff(self):
		log = logger.getLogger(levels = 'nodebug', lvldiff=['DEBUG', '-ERROR'])
		log.info('[>>>>>>>]You see this')
		log.info('[NO]You don\'t see this')
		log.info('[_NO]But you see this')
		log.info('[DEPENDS]You see this')
		log.info('[STDOUT]You see this')
		log.info('[STDERR]You see this')
		log.info('[ERROR]You DON\'T see this')
		log.info('[INFO]You see this')
		log.info('[DONE]You see this')
		log.info('[RUNNING]You see this')
		log.info('[CACHED]You see this')
		log.info('[EXPORT]You see this')
		log.info('[INPUT]You see this')
		log.info('[OUTPUT]You see this')
		log.info('[SUBMIT]You see this')
		log.info('[P.ARGS]You see this')
		log.info('[P.PROPS]You see this')
		log.info('[JOBDONE]You see this')
		log.info('[DEBUG]You SEE this')
		
if __name__ == '__main__':
	unittest.main()